<a href="https://colab.research.google.com/github/OlegBogutsky/nn2022/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Лабораторна робота № 2**
---
##Виконав Богуцький Олег, КН-31
#TensorFlow
Завдання:
За матеріалами ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)
Відповіді оформити .ipynb документами за кожним з попередніх пунктів
Викласти у зазначений репозіторій GitHub в окремій папці з назвою Lab2 де мають бути .ipynb файл та необхідні файли з даними
---
#Хід роботи

Завдання 1. Імпорт бібліотеки і перевірка працездатності.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


Завдання 2. Створення Tensor за допомогою tf.constant()

In [6]:
scalar = tf.constant(1)
print(scalar)

vector = tf.constant([1, 2])
print(vector)

matrix = tf.constant([[1, 2],
                      [3, 4]])
print(matrix)

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print(tensor)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


Завдання 3. Створення Tensor за допомогою tf.Variable()

In [7]:
tensor = tf.Variable([10, 7])
print(tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>


Завдання 4. Створення випадкових Tensor.

In [9]:
random = tf.random.Generator.from_seed(1)
random = random.normal(shape=(10, 10))
print(random)

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262  1.5658046  -0.1012345  -0.2744976
   1.4204658   1.2609464  -0.43640924 -1.9633987 ]
 [-0.06452483 -1.056841    1.0019137   0.6735137   0.06987712 -1.4077919
   1.0278524   0.27974114 -0.01347923  1.845181  ]
 [ 0.97061104 -1.0242516  -0.6544423  -0.29738766 -1.3240396   0.28785667
  -0.8757901  -0.08857018  0.69211644  0.84215707]
 [-0.06378496  0.92800784 -0.6039789  -0.1766927   0.04221033  0.29037967
  -0.29604465 -0.21134205  0.01063002  1.5165398 ]
 [ 0.27305737 -0.29925638 -0.3652325   0.61883307 -1.0130816   0.28291714
   1.2132233   0.46988967  0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827   0.4769051  -0.7812124  -0.996891
   0.33149973 -0.5445254   1.5222508   0.59303206]
 [-0.63509274  0.3703566  -1.0939722  -0.4601445   1.5420506  -0.16822556
  -0.4390865  -0.4129243   0.35877243 -1.9095894 ]
 [-0.2094769   0.8286217  -0.06695071 -0.35105535  1.0884082  -1.3863064
   0.88051325 -1.6833194   0.86754173 -0.1962

Завдання 5. Створення Tensor з нолями та одиницями.

In [11]:
print(tf.ones(shape=(5, 5)))
print(tf.zeros(shape=(10, 10)))

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


Завдання 6. Shape, size, rank.

In [16]:
random = tf.random.Generator.from_seed(1)
random = random.normal(shape=(10, 20))
print(random.shape)
print(random.ndim)
print(tf.size(random))

(10, 20)
2
tf.Tensor(200, shape=(), dtype=int32)


Завдання 7. Математичні операції.

In [25]:
random = tf.random.Generator.from_seed(1)
random = random.normal(shape=(2,2))
print(random)
print(random+10)
print(random-10)
print(random*10)
print(random/10)

print(random @ random)
print(tf.matmul(random, random))

random1 = tf.random.Generator.from_seed(1)
random1 = random1.normal(shape=(2,3))
random2 = tf.random.Generator.from_seed(1)
random2 = random2.normal(shape=(3,2))

print(random1)
print(random2)
print(tf.tensordot(random1,random2, axes=1))



tf.Tensor(
[[ 0.43842274 -0.53439844]
 [-0.07710262  1.5658046 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[10.438423   9.465602 ]
 [ 9.922897  11.5658045]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ -9.561577  -10.534398 ]
 [-10.077103   -8.4341955]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 4.3842273  -5.3439846 ]
 [-0.77102613 15.658046  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.04384227 -0.05343984]
 [-0.00771026  0.15658046]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.23341802 -1.0710559 ]
 [-0.15453117  2.4929476 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.23341802 -1.0710559 ]
 [-0.15453117  2.4929476 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.43842274 -0.53439844]
 [-0.07710262  1.5658046 ]
 [-0.1012345  -0.2744976 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.24122347 -1.0498914 ]
 [ 0.72207844 -0.919928  ]], shape=(2, 2), dtype=fl

Завдання 8. CRUD операції.

In [41]:
tensor = tf.Variable([10, 7])
print(tensor)


print(tensor[1])


tensor[1].assign(10)
print(tensor)

tensor = tf.Variable([[10, 7],[2,5]])
print(tensor)


print(tensor[1])


tensor[1].assign([10,2])
print(tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor(7, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>
tf.Tensor([2 5], shape=(2,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [10,  2]], dtype=int32)>


Завдання 9. Reshape, інтеграція з NumPy.

In [54]:
random = tf.random.Generator.from_seed(1)
random = random.normal(shape=(5,2))
print(random)

print(tf.reshape(random, shape=(2,5)))
print(tf.reshape(random, shape=(1,10)))

import numpy as np 

tensorNum = tf.constant(np.array([3, 7, 10]))
print(tensorNum)
print(np.array(tensorNum))

import pandas as pd 

tensorNum = tf.constant(pd.Series([1,2,3,4,5]))
print(tensorNum)
print(pd.Series(tensorNum))



tf.Tensor(
[[ 0.43842274 -0.53439844]
 [-0.07710262  1.5658046 ]
 [-0.1012345  -0.2744976 ]
 [ 1.4204658   1.2609464 ]
 [-0.43640924 -1.9633987 ]], shape=(5, 2), dtype=float32)
tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262  1.5658046  -0.1012345 ]
 [-0.2744976   1.4204658   1.2609464  -0.43640924 -1.9633987 ]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262  1.5658046  -0.1012345  -0.2744976
   1.4204658   1.2609464  -0.43640924 -1.9633987 ]], shape=(1, 10), dtype=float32)
tf.Tensor([ 3  7 10], shape=(3,), dtype=int64)
[ 3  7 10]
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
0    1
1    2
2    3
3    4
4    5
dtype: int64
